[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1", features = ["serde"] }
anyhow = "1.0"
tokio = { version = "1.14.0", features = ["sync"] }
bincode = "^1.3"
serde = { version = "^1.0", features = ["derive"] }