kind: Deployment
apiVersion: apps/v1
metadata:
  name: xlive-cache
spec:
  selector:
    matchLabels:
      app: xlive-cache
  replicas: 3
  template:
    metadata:
      labels:
        app: xlive-cache
    spec:
      containers:
        - name: xlive-cache
          image: wida/xlive-cache
          command: ["xlive-cache"]
          args: ["-r", "xlive-register-svc:9336"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9888
              name: service
            - containerPort: 3032
              name: monitor
---
kind: Service
apiVersion: v1
metadata:
  name: xlive-cache-svc
spec:
  selector:
    app: xlive-cache
  ports:
    - port: 9888
      name: service
      targetPort: 9888
    - port: 3032
      name: monitor
      targetPort: 3032
  type: LoadBalancer