kind: Deployment
apiVersion: apps/v1
metadata:
  name: xlive-origin
spec:
  selector:
    matchLabels:
      app: xlive-origin
  replicas: 2
  template:
    metadata:
      labels:
        app: xlive-origin
    spec:
      containers:
        - name: xlive-origin
          image: wida/xlive-origin
          command: ["xlive-origin"]
          args: ["-r", "xlive-register-svc:9336"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9878
              name: service
            - containerPort: 3032
              name: monitor
---
kind: Service
apiVersion: v1
metadata:
  name: xlive-origin-svc
spec:
  selector:
    app: xlive-origin
  ports:
    - port: 9878
      name: service
      targetPort: 9878
    - port: 3032
      name: monitor
      targetPort: 3032
  type: LoadBalancer