kind: Deployment
apiVersion: apps/v1
metadata:
  name: xlive-register
spec:
  selector:
    matchLabels:
      app: xlive-register
  replicas: 1
  template:
    metadata:
      labels:
        app: xlive-register
    spec:
      containers:
        - name: xlive-register
          image: wida/xlive-register
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9336
              protocol: UDP
            - containerPort: 3032
              name: monitor
---
kind: Service
apiVersion: v1
metadata:
  name: xlive-register-svc
spec:
  selector:
    app: xlive-register
  ports:
    - protocol: UDP
      port: 9336
      targetPort: 9336
  type: LoadBalancer